### ISSUE TITLE
add holiday allowance and 13th salary options 

### ISSUE THREAD

**Issue by stevermeister** [stevermeister/dutch-tax-income-calculator-old#1]

**Comment by JaTochNietDan** [comment]
:+1: for the holiday allowance, not sure how you go about calculating that though. Is it just straight up 8% of your gross yearly salary?

**Comment by stevermeister** [comment]
frankly speaking, still don't know all correct formulas for it. (of course, I'm not telling you about only 8%)
there are so many "specific" cases.
hope I'll figure it out soon.

**Comment by stevermeister** [comment]
@JaTochNietDan 
I've updated the app, please check it now. 
btw, I moved it to own domain - thetax.nl

**Comment by stevermeister** [comment]
already remove it. 
there were several users that did not like it

**Comment by zshamrock** [comment]
So, the final monthly net income, does it include or exclude holiday allowance? Would be nice just to have a small explanatory text, like "incl. or excl. holiday allowance", so we can manually add 8% on top.

**Comment by stevermeister** [comment]
@zshamrock feel free to make a pull request.
Once I added (8%) it as an option and that made it even more confusing.

**Comment by andrijeski** [comment]
I don't see the holiday allowance included on thetax.nl

Correct me if I'm wrong, but if the holiday allowance is included in the salary, you only need to divide the gross amount with 1.08 (if the holiday allowance is 8% of the gross salary), then use the result using the existing calculator.

**Comment by sean-wang-wenfeng** [comment]
@andrijeski  yes, your understanding is correct. I consulted the IND, it indeed calculates in this way. 
If the yearly gross is 30,000(before adding holiday allowance), then add 8% holiday allowance is 30k*1.08=32.4k. (32,400)

**Comment by stevermeister** [comment]
@andrijeski @sean-wang-wenfeng 
guys, lets come up with single solution which I will implement.
Should I divide or multiply? Does gross contain holiday allowance? (I think - yes, but it's opposite to last message)

**Comment by andrijeski** [comment]
@stevermeister to be honest, not sure what's the best way to do.
AFAIK, this depends from the contract. I've seen contracts where holiday allowance is included, and contracts where holiday allowance is on top of the agreed gross salary.

Maybe it is a good idea to add a check box for holiday allowance. For example, if it is checked, holiday allowance is included in the gross. Then you divide the real gross by 1.08  (given the holiday allowance is 8%).
If the allowance is on top of the base gross salary, then I don't think it needs to be included in this calculator.

The complicated part comes when the company is spreading the holiday allowance in 12 installments, along with the salary. This may be the case whether the holiday allowance is included in the base salary or added as an extra. The real net salary would be different.

Personally, I think that companies should provide clear information to the employees and tell them the real base salary without holiday allowance. For me it is enough for this website to have note regarding the holiday allowance, so the users can be aware of it.

**Comment by stevermeister** [comment]
ok, added.
![screen shot 2016-04-23 at 13 33 03](https://cloud.githubusercontent.com/assets/1526680/14761146/f34ec19a-0957-11e6-8721-e4bea880ca37.png)

enjoy the option ;)
