### ISSUE TITLE
Idea: Calculator for CGT (Capital Gain Tax)

### ISSUE THREAD

**Issue by nik-kashi** [stevermeister/dutch-tax-income-calculator-old#101]
As CGT in the Netherlands has different levels and is hard to calculate, it would be an interesting option.

**Comment by stevermeister** [comment]
@mohsenkashi could you please provide more details?

**Comment by ianbruton** [comment]
Hi, to try and revive this. 

I am looking for something like this for my crypto and stock assets for example.

Also the ability to consider trading that might be taxed at 51% due to certain circumstances.

https://broadstreet.nl/taxation-of-assets-box-3-in-the-netherlands/

**Comment by ianbruton** [comment]
holding btc over multiple years is taxed differently to day trading if it is classified that you are working at it for an example

**Comment by stevermeister** [comment]
if it's still actual you can reopen your issue here (new version of the application) - https://github.com/stevermeister/dutch-tax-income-calculator
