### ISSUE TITLE
Employer contributions

### ISSUE THREAD

**Issue by achigeor** [stevermeister/dutch-tax-income-calculator-old#103]
Hi, thanks for the great tool!

I have a question regarding the `Payroll Tax` and `Social Security Tax`. Are the amounts that I see on the tool, the total amounts payed by both the employee and employer? Or are there extra costs for the employer other than these two that do not appear in the calculation? For example, if one adds a 50k gross salary, is this total true cost of the employee for the employer? 

I was looking in https://github.com/stevermeister/dutch-tax-income-calculator-npm/blob/master/index.js to get a sense of how the calculations are happening but unfortunately it was not very clear.

Thanks!

**Comment by stevermeister** [comment]
Hi @achigeor,

thank you for your feedback.
There is always some specific from company to company, but in general - yes - 
**gross** - is the total amount that the company pays 

I would be happy to guide you with some clear documentation for it, but unfortunately, I didn't find one.
