### ISSUE TITLE
Ruling Percentage Calculation

### ISSUE THREAD

**Issue by tuterbatuhan** [stevermeister/dutch-tax-income-calculator-old#117]
Hi, first of all, thank you for this nice tool, it is great!
I would like to point to something in 30% Ruling percentage calculation. 

Please take this calculation as an example for explaining the situation:
![image](https://user-images.githubusercontent.com/14371920/123214416-79160a00-d4c7-11eb-8ccf-d98631871598.png)

You can see that the percentage (24%) is calculated in a way that the Yearly Taxable Income is 29.149 EUR (for 2020) however, it is stated by the [Dutch Tax Authorities](https://www.belastingdienst.nl/wps/wcm/connect/bldcontenten/belastingdienst/individuals/living_and_working/working_in_another_country_temporarily/you_are_coming_to_work_in_the_netherlands/30_facility_for_incoming_employees/conditions_30_p_facility/you_possess_a_specific_expertise) that the yearly taxable income **must be more than** this amount, not **equal**.
![image](https://user-images.githubusercontent.com/14371920/123214866-09544f00-d4c8-11eb-95ef-c48ed7c953f6.png)

For this reason, I think that the percentage can be calculated in a way that the Yearly Taxable Income is, for example, 29.150 EUR (minimum).

Cheers!

**Comment by stevermeister** [comment]
if it's still actual you can reopen your issue here (new version of the application) - https://github.com/stevermeister/dutch-tax-income-calculator
