### ISSUE TITLE
Bijtelling addition

### ISSUE THREAD

**Issue by rlilje** [stevermeister/dutch-tax-income-calculator-old#118]
It would be great to add the bijtelling rules to the calculator.

**Comment by stevermeister** [comment]
@rlilje is something about business car lease, but not income, right?

**Comment by rlilje** [comment]
HI @stevermeister, This is related to both business car lease and personal income. When I get a company lease car and drive 500km+ per year for personal use, I need to pay an extra tax called bijtelling on the value of the car. 
This amount is either 22% for a normal car or 12% for an electric car up to a threshold amount and after that 22%. The percentage is calculated on the value of the car. This means that if I earn for example €60 000 per year and have a car worth €30 000, 22% of the value of the car (€6600) will be added to my salary and I will be taxed as if I earn €66 600 per year. This will then impact the monthly income that I would receive.

**Comment by stevermeister** [comment]
@rlilje oh, wow, did not know about it. thank you for the information!
I will leave the issue open for now, maybe I or somebody else from contributors will have time for it in future

**Comment by stevermeister** [comment]
if it's still actual you can reopen your issue here (new version of the application) - https://github.com/stevermeister/dutch-tax-income-calculator
