### ISSUE TITLE
Holiday allowance checkbox confusing

### ISSUE THREAD

**Issue by DaJackkal** [stevermeister/dutch-tax-income-calculator-old#131]
Hey guys, 

Is it me or the holiday allowance checkbox is confusing? 

Plainly speaking, when I check the checkbox, in order to convey the fact that in my gross yearly income includes the holiday amount (8%, paid monthly rather than an extra payment), the netto monthly income decreases, which I find very odd. Is that a mistake or something is flawed in my own understanding of how that should work? Can someone explain please how can the monthly netto be lower when I also get an extra holiday payment every month?

Technically speaking, I can see that in the salary calculator, the holiday allowance is just substracted from the total taxable yearly amount, so I'd guess that the netto monthly income that is suspicious to me is only the netto monthly salary. So on top of that, I get whatever the netto amount of the 8% of the grossly income would be. If that's the case, I think it would make more sense to have also a field where you could see the _actual_ netto monthly income, the money hitting your bank account (netto monthly salary + netto monthly holiday allowance). 

I don't understand all the details and legal stuff, but this issue might be related to this discussion [https://github.com/stevermeister/dutch-tax-income-calculator/issues/99](url)

**Comment by stevermeister** [comment]
if it's still actual you can reopen your issue here (new version of the application) - https://github.com/stevermeister/dutch-tax-income-calculator
