### ISSUE TITLE
Difficult to click on the 'hours' box, it's covered by another (invisible) element

### ISSUE THREAD

**Issue by aSemy** [stevermeister/dutch-tax-income-calculator-old#132]
It's difficult to select the 'hours' box. It seems that only the bottom half of the input field is clickable

I'm not sure how to demonstrate this, if others aren't able to reproduce the issue.

When I inspect the HTML I think that the label for the box might be too large, but I'm just guessing.

<img width="768" alt="image" src="https://user-images.githubusercontent.com/897017/193308212-9f86504c-27c0-42f2-b830-71dde7dd0864.png">

I have the same problem on Chrome Android and Chrome MacOS.

**Comment by stevermeister** [comment]
@aSemy thank you for your feedback! 
I've been already working on the new version, you can check it here - https://thetaxnl2.netlify.app/

**Comment by stevermeister** [comment]
if it's still actual you can reopen your issue here (new version of the application) - https://github.com/stevermeister/dutch-tax-income-calculator
