### ISSUE TITLE
2023 Tax Data

### ISSUE THREAD

**Issue by alinalihassan** [stevermeister/dutch-tax-income-calculator-old#142]
There have been quite a few changes to the 2023 tax laws, and I was wondering if there are plans to support that.
I couldn't find the link with a clear description of everything, this is the best I could find: [here](https://www.loyensloeff.com/insights/news--events/news/update-dutch-wage-tax-changes-2023).

**Comment by alinalihassan** [comment]
If you'd like I can also start a PR in a few days if you're busy @stevermeister.

**Comment by alinalihassan** [comment]
It seems like you're already doing a lot of changes over at https://thetaxnl2.netlify.app/. It seems the data is there over at the new website. Is that going to be the new version? If so maybe we can write in the README that seems really useful to know haha. I'll close this issue if you agree.

**Comment by stevermeister** [comment]
@alinalihassan it's already there, just flush the cache :)

**Comment by stevermeister** [comment]
I'll update the code base as well and put this one into the archive

**Comment by stevermeister** [comment]
you can go here for the new codebase - https://github.com/stevermeister/dutch-tax-income-calculator
