### ISSUE TITLE
material design investigation 

### ISSUE THREAD

**Issue by stevermeister** [stevermeister/dutch-tax-income-calculator-old#16]

**Comment by yevgeniyvaleyev** [comment]
frameworks -  http://superdevresources.com/material-design-web-ui-frameworks/

**Comment by yevgeniyvaleyev** [comment]
http://materializecss.com/showcase.html - github stars 10.5K
http://material-ui.com/#/components/dialog - github stars 8.5K
http://bootswatch.com/paper/ - 6K
http://fezvrasta.github.io/bootstrap-material-design/ - 11.5K

https://www.polymer-project.org/0.5/docs/elements/material.html

**Comment by yevgeniyvaleyev** [comment]
http://bootswatch.com/paper/ - 6K

**Comment by yevgeniyvaleyev** [comment]
http://fezvrasta.github.io/bootstrap-material-design/ - 11.5K

**Comment by yevgeniyvaleyev** [comment]
I like first two.

**Comment by stevermeister** [comment]
if we are going to use Angular I think it's reasonable to look at 
https://material.angularjs.org

**Comment by yevgeniyvaleyev** [comment]
let's go for it, deal.
