### ISSUE TITLE
Take 2016 tax changes into account

### ISSUE THREAD

**Issue by JaTochNietDan** [stevermeister/dutch-tax-income-calculator-old#29]
The tax changes for 2016 are quite significant. I made the change already for the brackets since that's easy but I have no idea how the credits work...couldn't find any decent explanation on how to calculate your credits. Very confusing.

**Comment by stevermeister** [comment]
thank you for this pointing out!
I'll update them asap

**Comment by JaTochNietDan** [comment]
Sweet :+1:, thanks for your work on the credits, spent ages myself trying to figure out how they work but gave up in the end!

**Comment by stevermeister** [comment]
updated the brackets for 2016 and made it possible to calculate both (2015 and 2016).
credits are also not that clear for me, I just use constants, will figure it out
