### ISSUE TITLE
Update brackets to year 2014

### ISSUE THREAD

**Issue by lagivan** [stevermeister/dutch-tax-income-calculator-old#3]
Tax rates and brackets have been slightly updated in 2014. See here: http://www.expatax.nl/tax-rates-2014.php

**Comment by stevermeister** [comment]
thank you! 
I've updated formula for 2014 changes.
please check

**Comment by lagivan** [comment]
Looks good, thx. Could you deploy? http://stepansuvorov.com/useIt/dit/
