### ISSUE TITLE
Local setup error

### ISSUE THREAD

**Issue by teobais** [stevermeister/dutch-tax-income-calculator-old#34]
The following screenshot tries to make the argument mentioned on #33 a bit stronger:
![image](https://cloud.githubusercontent.com/assets/5684688/16853787/36edc2ec-4a0e-11e6-8cf5-dd8e05f45464.png)

OS: Windows 8 x64
npm version: 3.9.5

**Comment by stevermeister** [comment]
@toubou91 can't help you with Windows, sorry.

**Comment by stevermeister** [comment]
@toubou91 have you managed to solve it?
