### ISSUE TITLE
Effect of "holiday allowance included" button

### ISSUE THREAD

**Issue by Cy-napse** [stevermeister/dutch-tax-income-calculator-old#35]
Hello stevermeister

Really like your Dutch income tax calculator, so easy and useful! Thanks for this.

I have one question about it, I've been scratching my head trying to understand this: why does the "holiday allowance included" lower the taxable income and the net income? 

I may be thinking about this wrong or misunderstanding this (as I'm new to the Dutch tax system, I am considering moving to the Netherlands), but I can't make sense of it. I understand the holiday allowance to be also taxable income.

To take an example:
 If my employer tells me that my annual gross income is 100k
 and that the holiday allowance is included in that gross income
 it is taxable at the marginal rate
 so I would expect the taxable income to be 100k
 (and then the income tax to be 45,150 -- if under 65 years old and no 30% tax ruling)

But instead if I click the "holiday allowance included" button, it lowers the taxable income to 92,593! Why?

If the holiday allowance is not included and applies
 then does it not get added to the 100k
 so that the total taxable income is 108k?

Sorry if I am getting this wrong and am confused... please help me understand.

Thanks in advance for educating me on this!

**Comment by niklanus** [comment]
Hi @Cy-napse 

I'm pretty sure that the holiday allowance checkbox is there for the rare cases when you only know what your salary+holiday allowance is going to be.

You can enter either your annual gross income (and leave the checkbox unchecked) **OR** your annual gross income plus the holiday allowance (and check the checkbox) to calculate your taxable income, and you are going to get the same result.

Cheers!

**Comment by Cy-napse** [comment]
blockquote, div.yahoo_quoted { margin-left: 0 !important; border-left:1px #715FFA solid !important; padding-left:1ex !important; background-color:white !important; }  Hi Nik
Thank you for your reply and explanation. 
It sounds like you are implying that holiday pay is not taxable income. However I've read that in fact it is — eg,http://www.expatax.nl/kb/article/taxation-of-13th-month-holiday-allowance-and-pension-fund-442.html https://www.quora.com/I-have-an-8-annual-bonus-for-vacations-in-Netherlands-Is-this-gross-or-net 
So my understanding is that it is the total of salary + 13th month + holiday allowance that is taxed as annual gross income. 
If you did not have your holiday allowance included in the figure given to you, you'd have to calculate that and ADD it to the known figure  to get to your (higher!) total taxable income. 
(A tax adviser just did a simulation for me which confirms this.)
You may want to check this. Your tool is otherwise fantastic!
BestDavid 

Sent from Yahoo Mail for iPhone

On Sunday, August 7, 2016, 21:46, Nik Lanús notifications@github.com wrote:

Hi @Cy-napse 

I'm pretty sure that the holiday allowance checkbox is there for the rare cases when you only know what your salary+holiday allowance is going to be.

You can enter either your annual gross income (and leave the checkbox unchecked) OR your annual gross income plus the holiday allowance (and check the checkbox) to calculate your taxable income, and you are going to get the same result.

Cheers!

**Comment by stevermeister** [comment]
@Cy-napse 

the logic is pretty simple: you have gross year amount and net month amount based on this amount. If you have holiday allowance(that is paid separately) included in your gross amount - it means that you will get less income each month.

so basically when you click "holiday allowance included" it just deduct this amount from you salary. 

I agree that it's good to show also amount that will be paid separately, will improve it in V3
