### ISSUE TITLE
Calculated tax credits don't match Belastingdienst examples

### ISSUE THREAD

**Issue by bdewater** [stevermeister/dutch-tax-income-calculator-old#36]
The examples for the [general tax credit](http://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/algemene_heffingskorting/algemene_heffingskorting_inkomensafhankelijk/tabel_ahk_2016) and the [labour tax credit](http://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/arbeidskorting/tabel_arbeidskorting_2016) do not match the results from the site. All data for is for pre-pension age in 2016:

| General tax credit | 18k gross | 50k gross | 70k gross |
| --- | --- | --- | --- |
| thetax.nl | 2103 | 1496 | 1366 |
| Belastingdienst.nl | 2242 | 792 | 0 |

| Labour tax credit | 65k gross |
| --- | --- |
| thetax.nl | 1126 |
| Belastingdienst.nl | 1864 |

**Comment by bdewater** [comment]
Given the comment at https://github.com/stevermeister/dutch-tax-income-calculator/issues/29#issuecomment-169831290 - the links also have the formulas 😄

**Comment by pcriv** [comment]
+1

**Comment by stevermeister** [comment]
@bdewater thank you very much for providing this information! 
I've updated the app, please check it now http://thetax.nl/

**Comment by bdewater** [comment]
@stevermeister in f31309a4fadaf34adbeca7fd0471c93c1123222f only the 2016 numbers were added. The numbers/formulas for 2015 are slightly different, e.g. for 18k gross the general tax credit is 2203.

**Comment by stevermeister** [comment]
you are right. 
completely forgot about it. 
already skipped calculations for 2015 for new version - https://github.com/stevermeister/dutch-tax-income-calculator2

do you think it's useful?

**Comment by bdewater** [comment]
It's not really interesting as other tax rebates probably have a larger impact on your financial life. But if you have a year selector, it should show proper values :)
