### ISSUE TITLE
Effect of social security button

### ISSUE THREAD

**Issue by Bemmu** [stevermeister/dutch-tax-income-calculator-old#37]
The app should explain a bit what it means to check "social security".

Does it mean that if that is checked, then health insurance cost gets included?

**Comment by stevermeister** [comment]
good point, I working on next version of the app and will try to cover it there. 

> social security

it's what usually company pays for you, quite a broad topic. and it's nothing to do with health insurance

**Comment by stevermeister** [comment]
I'll probably remove this option in new version at all, because in almost all the cases it's ON

**Comment by Bemmu** [comment]
So should it be "Are you self-employed" ?

**Comment by stevermeister** [comment]
I think it's something different
