### ISSUE TITLE
security concerns

### ISSUE THREAD

**Issue by AddaxSoft** [stevermeister/dutch-tax-income-calculator-old#38]
I've noticed couple of privacy / security issues:
- URL displays salary info 
- no use of HTTPS (TLS/SSL)

Information related to tax / salary is sensitive and needs to be encrypted.

**Comment by stevermeister** [comment]
@AddaxSoft 
thank you for the feedback! 
- URL - it was made for convenience if you would like to share the link - would you recommend an alternative way?
- HTTPS - yes, 100% true, I've already bought the certificate, but then realised that github-pages (where it's hosted) are not supporting HTTPS with cursom domain name

**Comment by AddaxSoft** [comment]
Thanks for your quick reply! 
- URL: Yes I do, always pass variables via POST requests - at least the ISP and company logs files won't have your salary :)
- HTTPS: I suggest to buy a domain and host it on your own. If you want to cover the costs put some ads. The idea is quite simple and Google gives your page the best ranking for tax net salary calcuator which should drive lot of traffic to you 

good luck!
let me know if you need help with security ;)

**Comment by stevermeister** [comment]
- URL: data is sent via ajax not via url. I'm changing the URL to make it convenient - to send the link to your friend, coworker or recruiter with exact calculations. If you tell me how to keep this convenient option and also make it secure - I'll definitely do it.
- HTTPS: will do it probably after producing version 2 on which I'm currently working on - https://github.com/stevermeister/dutch-tax-income-calculator2

**Comment by JorgeAnzola** [comment]
Or check https://letsencrypt.org/

**Comment by stevermeister** [comment]
@JorgeAnzola it's great, but currently project is hosted on github pages and for now it does not support https for custom domain names

**Comment by eduardomourar** [comment]
@stevermeister, maybe you can make thetax.nl redirect to the github pages, because pages already accepts HTTPS protocol.

**Comment by AddaxSoft** [comment]
I recon the idea of letsencrypt.org - you can get SSL cert and configure your server in less than 10 mnts

**Comment by simonacca** [comment]
I very much like the idea of saving the app's data as a query string, but I am concerned, like you all, about privacy.
So I deployed the app on netlify: https://thetaxnl.netlify.com
@stevermeister If you point the official domain to their servers, they would also provision a certificate for it, for free (letsencrypt). They also integrate with github, so netlify would build the project every time there's a new commit.

If you like this solution I can transfer the administration of the project on netlify to you, let me know :)

**Comment by stevermeister** [comment]
@simonacca that's a great suggestion!
and it was really easy to implement

so now enjoy HTTPS -  https://thetax.nl
🎉 🎉 🎉
