### ISSUE TITLE
suggestion: collect data to offer avg salary / expectation in the NL market

### ISSUE THREAD

**Issue by AddaxSoft** [stevermeister/dutch-tax-income-calculator-old#39]

**Comment by stevermeister** [comment]
you just suggested to protect data from being tracked here - https://github.com/stevermeister/dutch-tax-income-calculator/issues/38

and now suggest to track? :)
it's really great to have such stat, but it would be unfair for users, I guess

**Comment by AddaxSoft** [comment]
data can always be collected for good to make better decision. 
Example: collect data anonymously, or give the user to have a chance to share data.

**Comment by stevermeister** [comment]
ok, when V2 is ready I'll think about it. Thank you for sharing your ideas!
