### ISSUE TITLE
LSEP unicode characters in live version

### ISSUE THREAD

**Issue by teobais** [stevermeister/dutch-tax-income-calculator-old#41]
Here's what I'm talking about:
![image](https://cloud.githubusercontent.com/assets/5684688/21722801/72d62b50-d42e-11e6-8527-b847522b999b.png)
Without having seen the commits' history, I suspect it happened due to usage of different machines; it is generally encountered in Mac devices and as I have already been facing this issue quite a few times in the past, [this ](http://stackoverflow.com/questions/16552315/removing-unicode-line-separator-in-bash) answer helped me out.

**Comment by stevermeister** [comment]
thank you!
it looks like it's fixed, please check

**Comment by teobais** [comment]
Indeed!
