### ISSUE TITLE
"show calculations" feature

### ISSUE THREAD

**Issue by AddaxSoft** [stevermeister/dutch-tax-income-calculator-old#42]
It will be super helpful in case you have to show details of how calculations were made in case of debate between employee and payroll for example.

Thanks!

**Comment by stevermeister** [comment]
completely agree, will keep it for now here and will take in account for next version

**Comment by stevermeister** [comment]
I'm still dreaming of having time to make a nice animation for it :)

**Comment by eduardomourar** [comment]
With PR #94 , this should be possible by doing some small modification. We can present to the user the brackets and rates used during the calculation.
