### ISSUE TITLE
Calculation issues with 30% ruling not full

### ISSUE THREAD

**Issue by eduardomourar** [stevermeister/dutch-tax-income-calculator-old#43]
Regarding the 30% facility, as you can check in other websites, there is a possibility of having from 0% to 30% tax free allowance and the tool is not considering it.

In the [Expatax.nl](https://www.expatax.nl/30ruling) they give a lot of information, like this:
> Since the law requires a minimum taxable salary and doesn't mention the gross salary and also states that under the 30% ruling a tax free allowance can be paid of up to 30%, it is possible to reduce the tax free allowance to a lower percentage as such that the minimum required taxable salary is met.

I will give a hypothetical case of EUR 39,000 year income in 2017. The tool is giving this with 30% ruling:
![thetax](https://cloud.githubusercontent.com/assets/16357187/22391386/0aa79a54-e4d8-11e6-9caa-8acbef6582b0.png)

But we have 2 scenarios to be considered here (probably add another checkbox):
- Employee with a master’s degree and younger than 30 years

The calculation of 70% is working alright when the year gross amount is more or equal to EUR 40,178, but it not considering proportional when it is between EUR 28,125 and EUR 40,178.

The proper calculation should use only the minimum taxable income (variable minimumIncome), which is EUR 28,125, and add that non taxable income difference (variable rulingDiff) [39,000 - 28,125 = 10,875] to the year net income. Like this:
**Taxable Income:	28125**
Income Tax:	10625
General Tax Credit:	1846
Labour Tax Credit:	3103
**Year net income:	22449 + 10875 = 33324**
Monthly net income:	2777

- Other employees

The calculation of 70% is working alright when the year gross amount is more or equal to EUR 52,857, but it not considering proportional when it is between EUR 37,000 and EUR 52,857.

The proper calculation should use only the minimum taxable income (variable minimumIncome), which is EUR 37,000, and add that non taxable income difference (variable rulingDiff) [39,000 - 37,000 = 2,000] to the year net income. Like this:
**Taxable Income:	37000**
Income Tax:	14246
General Tax Credit:	1418
Labour Tax Credit:	3184
**Year net income:	27356 + 2000 = 29356**
Monthly net income:	2446

So in the end the math will be like this in the calc.component.js file:
```
let rulingDiff = 0;
this.salary.taxableYear = grossYear;
if(this.salary.ruling && this.salary.taxableYear > minimumIncome){
  this.salary.taxableYear = this.salary.taxableYear * 0.7;
  if (this.salary.taxableYear < minimumIncome){
    rulingDiff = grossYear - minimumIncome;
    this.salary.taxableYear = minimumIncome;
  }
}
this.salary.generalCredit = getAlgemeneHeffingskorting(this.salary.taxableYear);
this.salary.labourCredit = getArbeidskorting(this.salary.taxableYear);
this.salary.grossMonth = ~~(grossYear / 12);
this.salary.netYear = grossYear - getTaxAmount(this.salary.taxableYear, this.salary.socialSecurity, this.year);
this.salary.netYear += this.salary.generalCredit + this.salary.labourCredit + rulingDiff;
```
I tried my best to keep this issue simple, but with enough details.

Anyhow, thanks a lot for this great tool!

**Comment by stevermeister** [comment]
still not implemented, but really nice to have

**Comment by BBagnato** [comment]
Would be really great to have option for ruling and ruling real percentage for under 30 with Master's degree.
