### ISSUE TITLE
Contract other than 40 hours working week

### ISSUE THREAD

**Issue by eduardomourar** [stevermeister/dutch-tax-income-calculator-old#44]
There is an improvement to be made to the tool regarding the amount of working hours.

It assumes the 40 hours working week, but other options would be 36, 38 or 45 (and many more). With different working hours, the monthly amount would vary.

Another suggestion would be to, in addition to monthly salary, have it per week, day and hour.

**Comment by stevermeister** [comment]
thank you for you feedback, 
I think option that you described is more for advanced mode, that I'm going to implement somewhere in future.
