### ISSUE TITLE
Add mobile web app features with manifest.json

### ISSUE THREAD

**Issue by shershen08** [stevermeister/dutch-tax-income-calculator-old#45]
That could add more native-like UI, such as:
 - icon and title for desktop
 - mobile browser top bar colouring 
etc.

**Comment by stevermeister** [comment]
it's open source, so you are more than welcome to make a PR for it. because any way I did not get the point about manifest.json

**Comment by shershen08** [comment]
the http://thetax.nl/manifest.json is not available, manifest.json and the icon should be added to build process so that thosa are visible

**Comment by stevermeister** [comment]
true, thx

**Comment by AchoArnold** [comment]
I think this will be closed by https://github.com/stevermeister/dutch-tax-income-calculator/pull/78
