### ISSUE TITLE
Wrong Taxable Income when Holiday allowance included selected

### ISSUE THREAD

**Issue by koraykupe** [stevermeister/dutch-tax-income-calculator-old#48]
Hi,

Holiday allowance is taxable but when user select the checkbox it reduces amount of Taxable Income. It's wrong.

I saw it on some reliable websites like iamsterdam.com

Quote: "There are special regulations regarding pension premiums, but the bonus, holiday allowance, benefit package and company car fall under the ruling."

**Comment by stevermeister** [comment]
ok, but it still nothing to do with NET monthly net, right? 

I admit that checkbox is pretty confusing: it means that we already have holiday allowance in provided GROSS, so to get TAXABLE AMOUNT we need to deduct it

**Comment by koraykupe** [comment]
Ok, I think It's confusing. Let's assume my gross salary is 50K (inc holiday allowance) and I have I have 30% ruling. If I select all checkboxes It shows the taxable salary as 32,407. The rule says min taxable income amount must be higher than 37000. So, I am not in the 30% rule by this calculation.

We need to calculate 70% of gross salary to find the taxable salary. 

Quote (by 2016 requirements):

> A common mistake is to think that this means that your minimum annual gross salary should be € 52,699 to get the 30% ruling. People think so, because 100/70 x € 36,889 = € 52,699 and 70% of € 52,699 is € 36,889. In fact, the minimum gross salary is € 36,889. This is because your employer can also pay you € 0 as a tax-free allowance under the 30% ruling. This way, future pay rises can be paid to you tax free under the 30% ruling, until your gross salary is € 52,699.

I think If the rule is accepted by employer, It can be adjusted. (I am not sure but lots of resources say it) If gross salary is less than 52857 we can benefit the rule partially.

So, with 50K gross, It is possible to get 30% advantage partially (close to full).

It would be good to show a warning If we benefit 30% advantage fully/partially.

**Comment by stevermeister** [comment]
Yes, I agree that it could be confusing.
I removed and then added back this holiday allowance option check several times.

> It would be good to show a warning If we benefit 30% advantage fully/partially.

I'll put in my notes for version 2, thank you
