### ISSUE TITLE
Hour Income is not affected by the weekly working hours input

### ISSUE THREAD

**Issue by simonacca** [stevermeister/dutch-tax-income-calculator-old#58]
## Steps to reproduce:

- insert a sample yearly income, let's say 30.000EUR.
- open "advanced options"
- toggle "hour gross income". 
- You will see a value of 28EUR/h for "hour gross income".
- Modify the value of "weekly working hours" from 40 to 20.

## Expected behaviour:

The value for "hour gross income" doubles

## Observed behaviour:

The value for "hour gross income" has not changed

## Workaround

I have found that if you modify the value of "Gross Income" at the top, the "hour gross rate" is finally updated.

**Comment by stevermeister** [comment]
can't reproduce.
could you please make a screen recording for this issue?

**Comment by simonacca** [comment]
Sure, here it is: https://youtu.be/bitAOwQMah0
Basically the second time I highlight text, that should already be a 28, instead of 14, I think.

**Comment by stevermeister** [comment]
yes, now I see it, thank you very much!

**Comment by stevermeister** [comment]
fixed, please check

**Comment by simonacca** [comment]
Works perfectly, thank you for fixing this so quickly!
