### ISSUE TITLE
i18n (for ru and other)

### ISSUE THREAD

**Issue by inezhynskiy** [stevermeister/dutch-tax-income-calculator-old#60]
Hi. Is it possible to add russian version of canculator to your site http://thetax.nl ? If you want I can help with translation

**Comment by stevermeister** [comment]
Hi,

we already working on new version of the app, 
you can check beta here - http://beta.thetax.nl/ 
and the code base is here - https://github.com/stevermeister/dutch-tax-income-calculator2
it would be great if you could check the correctness of Russian translations

**Comment by stevermeister** [comment]
@inezhynskiy 
I returned back to an idea for a significant update of the application. 
here you can see how it looks - https://thetaxnl2.netlify.app/

I'm thinking about how critical localization would be here. I just want to keep it as simple as possible.

**Comment by stevermeister** [comment]
if it's still actual you can reopen your issue here (new version of the application) - https://github.com/stevermeister/dutch-tax-income-calculator
