### ISSUE TITLE
2018 data

### ISSUE THREAD

**Issue by noloman** [stevermeister/dutch-tax-income-calculator-old#64]
Hi,

It would be nice to have the calculations for 2018.
Thanks a lot for the work, it is tremendously helpful!

**Comment by stevermeister** [comment]
yes, sure, here the PR with an update for 2018 - https://github.com/stevermeister/dutch-tax-income-calculator/pull/65/files

still not sure about some numbers so it would be great if you help me to find them

some of the numbers I found here - https://www.tax-consultants-international.com/read/16946?sublist=3275&parent2=4772&submenu=4772

**Comment by noloman** [comment]
Yes indeed, I think should numbers should be correct, since they are the same as here:
https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/boxen_en_tarieven/overzicht_tarieven_en_schijven/u-hebt-voor-2018-de-aow-leeftijd-bereikt

**Comment by stevermeister** [comment]
thank you for the link, I've updated all the numbers for 2018
please check it's already live http://thetax.nl/
