### ISSUE TITLE
A note about income tax calculation

### ISSUE THREAD

**Issue by TheBlueSky** [stevermeister/dutch-tax-income-calculator-old#66]
There is something that doesn't seem right here. I compared the numbers from http://thetax.nl/ and https://www.blueumbrella.nl/ (looks like these guys are in tax business) and got the following:

Gross Income: €50,000 | thetax.nl | blueumbrella.nl
--------------- | --------------- | ---------------
Taxable Income | €37,000 | €37,296
Payroll Tax | -€4,849 | N/A
Social Security Tax | -€9,399 | N/A
Healthcare premium* | N/A | -€2,107
General Tax Credit | €1,476 | €1,462
Labour Tax Credit | €3,109 | €3,098
Total Income Tax | -€9,664 | -€9,809
Net Income | €40,336 | €40,191

Gross Income: €55,000 | thetax.nl | blueumbrella.nl
--------------- | --------------- | ---------------
Taxable Income | €38,500 | €38,500
Payroll Tax | -€5,462 | N/A
Social Security Tax | -€9,399 | N/A
Healthcare premium* | N/A | -€2,175
General Tax Credit | €1,405 | €1,405
Labour Tax Credit | €3,055 | €3,055
Total Income Tax | -€10,401 | -€10,400
Net Income | €44,599 | €39,650

Gross Income: €60,000 | thetax.nl | blueumbrella.nl
--------------- | --------------- | ---------------
Taxable Income | €42,000 | €42,000
Payroll Tax | -€6,892 | N/A
Social Security Tax | -€9,399 | N/A
Healthcare premium* | N/A | -€2,373
General Tax Credit | €1,241 | €1,241
Labour Tax Credit | €2,929 | €2,929
Total Income Tax | -€12,120 | -€12,120
Net Income | €47,880 | €42,480

\* I don't know what "Healthcare premium" is; just assumed it's a deduction

These examples show the same or close numbers for "Taxable Income", "General Tax Credit", "Labour Tax Credit", and "Total Income Tax"; however, "Net Income" is vastly different numbers the more "Gross Income" is.

**Comment by stevermeister** [comment]
@TheBlueSky thank you for verifying the calculations!
The logic is pretty straightforward. Don't know why they have different numbers. Unfortunately, they are not opensource and we cannot check their calculations.

**Comment by TheBlueSky** [comment]
@stevermeister no issues, maybe their numbers aren't correct.
I checked couple of other websites (some not up-to-date), but got mostly numbers closers to yours.
Thanks.
