### ISSUE TITLE
Tax Calculation for 2019

### ISSUE THREAD

**Issue by sathishmurugesan** [stevermeister/dutch-tax-income-calculator-old#71]
Could you please update calculation to also reflect 2019 tax calculation?

Thanks,
Sathish

**Comment by stevermeister** [comment]
if you could provide me numbers([here](https://github.com/stevermeister/dutch-tax-income-calculator/blob/master/src/data.json) you can find current ones ) for 2019 I'll do it.
or you can do it yourself and make a nice pull request, it's open source ;)

**Comment by thilak-rao** [comment]
I'll send a pull request for this as soon as I find the numbers.

**Comment by srid99** [comment]
@stevermeister created a [PR for 2019](https://github.com/stevermeister/dutch-tax-income-calculator/pull/75).

Gathered information from below sites,

rulingThreshold
https://www.belastingdienst.nl/wps/wcm/connect/nl/wonen-of-werken-buiten-nederland/content/voorwaarden-30-procent-regeling

payrollTax (table 1), socialPercent (table 5 and 6), generalCredit (table 2a), labourCredit (table 2a)
https://download.belastingdienst.nl/belastingdienst/docs/nieuwsbrief-loonheffingen-2019-lh2091t94fd.pdf

generalCredit
https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/algemene_heffingskorting/tabel-algemene-heffingskorting-2019

labourCredit
https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/arbeidskorting/tabel-arbeidskorting-2019

Also used 2018 tax tariff as a reference to see how it's done,
https://download.belastingdienst.nl/belastingdienst/docs/nieuwsbrief_loonheffingen_2018_lh2091t84fd.pdf

**Comment by stevermeister** [comment]
**Updated.**

Only one small thing, I've already implemented service workers offline cache and now to have new version you need to deregister service worker that is not that convenient :(

**Comment by srid99** [comment]
Ah, I see. With incognito mode I do see the changes. Is there a way to invalidate this cache? At least a way to communicate the user base? If it's not there yet, maybe having some information on "how to invalidate cache" in the page would help (non-developer) users (for future).

**Comment by srid99** [comment]
We could have a link in the page to invalidate the service worker cache, something with the solution provided in the link.

https://github.com/GoogleChromeLabs/sw-precache/issues/340#issuecomment-349982432

**Comment by stevermeister** [comment]
I think it should be more clever way to do updates

**Comment by stevermeister** [comment]
ok, I've updated the sw version, now it should work :)

**Comment by joelbasson** [comment]
Thanks for the update. But why does the difference in 2018 vs 2019 not match up to example given here?
https://www.rijksoverheid.nl/onderwerpen/belastingplan/belastingwijzigingen-voor-ons-allemaal/tweeschijvenstelsel-inkomstenbelasting

Use the examples of €35k and €65k

**Comment by stevermeister** [comment]
could you please make a screenshot of example? I could not find it

**Comment by joelbasson** [comment]
In the example they give, Sarah earns €65k and should receive €1205 more in 2019 (vs 2018) and €1565 in 2021 (vs 2018).
In your excellent app, the difference is €675
It could also be that my Dutch has let me down (And then this is embarrassing) :)

**Comment by srid99** [comment]
> Thanks for the update. But why does the difference in 2018 vs 2019 not match up to example given here?
> https://www.rijksoverheid.nl/onderwerpen/belastingplan/belastingwijzigingen-voor-ons-allemaal/tweeschijvenstelsel-inkomstenbelasting
> 
> Use the examples of €35k and €65k

@joelbasson thanks for validating. I see what you mean. The information I provided is still based on four-bracket system whereas in rijksoverheid, in the example they used, is using two-bracket system to calculate for 2019. My understanding on two-bracket system is that it will be implemented gradually by 2021. I used the [newsletter from belastingdienst](https://download.belastingdienst.nl/belastingdienst/docs/nieuwsbrief-loonheffingen-2019-lh2091t94fd.pdf) (published on 21st Dec 2019) as reference for payroll tax and general credit tax which still has 4 brackets. Also the english version of the [Tax Plan 2019](https://www.andersentaxlegal.nl/media/1188/andersen-tax_2019-tax-plan_eng_final.pdf) (still have to improve my Dutch) states that 2019 will have 4 brackets.

As I mentioned, I am not fluent in Dutch (yet). So it can be very well me who did some mistake (very unlikely) and the information in the rijksoverheid site is correct ;)

**Comment by joelbasson** [comment]
In their example https://www.rijksoverheid.nl/onderwerpen/belastingplan/belastingwijzigingen-voor-ons-allemaal/tweeschijvenstelsel-inkomstenbelasting they still have the 4 brackets for 2019, but the first three rates are adjusted to be more similar to each other (36.65%, 38.10% and 38.10%) which should result in a increase of take home pay of €1205 in 2019. Only in 2021 do they switch to 2 brackets which results in the increase to €1565

**Comment by stevermeister** [comment]
@joelbasson I would be happy to fix the bug (if it's there), but I need test data: trusted input and output. From what you are saying I only heard about difference between salaries

**Comment by srid99** [comment]
@stevermeister so tested with my Jan month payslip and I see a 3 euro difference (3 euro more than what it's been calculated here). I did the same with Dec 2018 payslip and it had 4 euro difference (with 2018 tax of course, 4 euro more than what's been calculated). So overall it seems to work, not accurate though but good enough.
