### ISSUE TITLE
Car leasing calculation

### ISSUE THREAD

**Issue by Alevale** [stevermeister/dutch-tax-income-calculator-old#81]
Could there be any way to add "car leasing" costs to the calculator?

I know this might be quite tricky, but I wanted to have the calculation of this and there was literally nothing that I could search up to make it.

I am not talking about the normal calculation of the road taxes (which you have underneath the page) but the one that would be taken as "company car" for private use.

Considering the next example:

Gross Income: XXXXX
Company contribution for company car: YYYY
Lease car per month (w or w/ BTW?): ZZZZ
Private use: Y/N
Bijtelling brutto: TTTTT (Could use some other place to make the calculation, or just be filled by the user)

End salary... (No clue how this is calculated sadly 😢)
I think it's

Gross + Company contribution - Lease car per month - Bijtelling per month
Still not fully sure 😅 

Hope it helps!

**Comment by stevermeister** [comment]
thank you for sharing the idea!
I'll keep it in mind for the next update.
Please provide as much information as possible, ideally with real number examples that I can check calculations

**Comment by Alevale** [comment]
@stevermeister I'll try to add details here as soon as I have one salary in which this is applied (in quite some months), even though I am no expert in taxes... Still might be better than no information.

Maybe we could have something like a more advanced tax calculator (something for like extra cases, and with switches and such...)

**Comment by stevermeister** [comment]
@Alevale please fill free to add details later, for now, I'll close the issue
