### ISSUE TITLE
API for calculating the tax amount

### ISSUE THREAD

**Issue by Alevale** [stevermeister/dutch-tax-income-calculator-old#83]
It would be nice to be able to have an API that answers with the results for a providen amount.

Now the way the app works is fine, but if there could be an api, maybe some excel sheets or different tools could be using this to make calculations. OFC there could be issues, but it's still way better than manually having to put the income.

**Comment by stevermeister** [comment]
@Alevale thank you for sharing your idea!
for now, it's just frontend app with the logic build-in the application, 
but I'll keep it issue open, maybe in future I'll have some spare time to bring your idea to life.

**Comment by stevermeister** [comment]
@Alevale now there is an npm package - https://www.npmjs.com/package/dutch-tax-income-calculator
that you can deploy and build your own API based on it.
