### ISSUE TITLE
44k has bigger net salary than 45k when 30% young enabled

### ISSUE THREAD

**Issue by FrancescoBorzi** [stevermeister/dutch-tax-income-calculator-old#85]
https://thetax.nl/?salary=44000&ruling=1&socialSecurity=1&year=2019&allowance=1&startFrom=Year&retired=0&rulingChoice=young

https://thetax.nl/?salary=45000&ruling=1&socialSecurity=1&year=2019&allowance=1&startFrom=Year&retired=0&rulingChoice=young

**Comment by stevermeister** [comment]
that's really strange for some reason you are getting much more tax free for 44k:
https://thetax.nl/?salary=44000&ruling=1&socialSecurity=1&year=2019&allowance=1&startFrom=Year&retired=0&rulingChoice=young
https://thetax.nl/?salary=45000&ruling=1&socialSecurity=1&year=2019&allowance=1&startFrom=Year&retired=0&rulingChoice=young

**Comment by baitun** [comment]
It seems that the corner case is between annual salary `44263` and `44264`. And it happens, only if `Young employee with masters` selected (`ruling.choice=young`)
UPD: and when `Holiday allowance included` checked

**Comment by baitun** [comment]
It seems that the reason in this code:

https://github.com/stevermeister/dutch-tax-income-calculator/blob/a59e53bd1b5a56a69a6cb9a369287f2439777f4e/src/calc/calc.component.js#L226-L233

**Comment by stevermeister** [comment]
@baitun thank you for sharing the conclusions of your research.
indeed, that's a strange condition
> salary.taxableYear > rulingIncome

**Comment by stevermeister** [comment]
@baitun I've check the condition - it's correct - it means that if you taxableYear amount is less than rulingIncome requirements - the ruling is not applicable

**Comment by stevermeister** [comment]
but this one is really strange:

`if (salary.taxableYear < rulingIncome) { // For partial `

I commented it out for now and looks like it works correctly now.

**Comment by tiagofilipe1** [comment]
By commenting out that condition you have disabled the possibility of having a partial 30% rule (anything from 1 to 29%), thus making the 'Ruling real percentage' option useless.
Could you add the condition back please?

**Comment by stevermeister** [comment]
@tiagofilipe1 thank you for your feedback.
for some reason, this condition is the cause of an issue described above.
Could you maybe suggest a solution to cove both cases?

**Comment by tiagofilipe1** [comment]
I do not have a solution that covers both cases, no.
However, it seems to me that the root of the problem that originated in this topic (44k > 45k) is somewhere else in the code. Removing the condition mentioned above just happens to fix this specific case by breaking a significant and important aspect of the calculations (the partial ruling).
