### ISSUE TITLE
The tax brackets are wrong for 2020

### ISSUE THREAD

**Issue by sevilyilmaz** [stevermeister/dutch-tax-income-calculator-old#91]
It's announced that there will be 2 brackets (up to € 68,508 37.35%, from € 68,508 49.50%) for 2020. ([ref](https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/boxen_en_tarieven/overzicht_tarieven_en_schijven/u-hebt-in-2020-nog-niet-aow-leeftijd)) which makes the brackets that are added with this commit wrong: 1fd5304

Could you please update the tax brackets?

**Comment by stevermeister** [comment]
hm, no low rate tax at all? it looks a bit strange for me. 

@baitun could you please join the discussion? as an author of PR with changes for 2020.

**Comment by baitun** [comment]
I took these numbers from [this site](https://meijburg.com/news/budgetday-2019-changes-payroll-taxes).

I'm not 100% sure how does it work, but in this tax rate, there is also included `National Insurance Contribution`, which is 27.65% and calculated separately (in [social percent section](https://github.com/stevermeister/dutch-tax-income-calculator/blob/03fddd1155a2707d556fb1021d0af9127351f531/src/data.json#L192)).

Also for example, for the 2019 tax rate for income up to € 34,300 is `38.10%` ([ref](https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/boxen_en_tarieven/overzicht_tarieven_en_schijven/u-hebt-in-2019-nog-niet-aow-leeftijd)), but in [file](https://github.com/stevermeister/dutch-tax-income-calculator/blob/03fddd1155a2707d556fb1021d0af9127351f531/src/data.json#L158) it's `10.45%` (`38.10% - 27.65%`).

**Comment by stevermeister** [comment]
@sevilyilmaz I'm still trying to figure out what's the correct way here.
just to remove the first bracket is not correct, I guess. 
If you compare how it worked for 2019, you will see that it was also this first bracket based on National Insurance
...well basically I just rephrase what @baitun already said

**Comment by stevermeister** [comment]
@sevilyilmaz fill free to reopen you can give exact case with wrong calculations
