### ISSUE TITLE
Labour tax credit 2020 calculation

### ISSUE THREAD

**Issue by bryancresswell** [stevermeister/dutch-tax-income-calculator-old#93]
I am calculating the labour tax for different amounts, and I notice that the labour tax amount algorithm doesn't really match the official calculation as listed here: 

https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/arbeidskorting/tabel-arbeidskorting-2020

Using the same algorithm for the general tax credit, I get the same numbers. 

Assuming one's annual is 90000 EUR. If we then look at the taxable section of it, and calculate the labour credit, basing it on the formula shown in the link:

`€ 3.819 - 6% x (labor income - € 34.954)`

We then get:

`€ 3.819 - 0.06 x (€ 60000 - € 34.954)`

Which equates to: € 516.24. However, the tool calculates it as € 292. Calculating it based on the 2019 tax, it seems that I am able to obtain the same values via the formula/the tool. This makes me think that the algorithm isn't updated to calculate the new labour tax credit formula for 2020. If it is confirmed, I will be more than happy to submit a PR.

**Comment by stevermeister** [comment]
@bryancresswell thank you for your feedback, I think you are right `Labour tax credit` method should be rewritten, if you could make a PR it would be great
