### ISSUE TITLE
Add automated testing to project

### ISSUE THREAD

**Issue by eduardomourar** [stevermeister/dutch-tax-income-calculator-old#95]
@stevermeister, we have already discussed this and I think that is quite important to have automated testing in the project. I have found that the we can download a spreadsheet containing the calculation for multiple salaries in the [belastingdienst website](https://www.belastingdienst.nl/wps/wcm/connect/nl/personeel-en-loon/content/hulpmiddel-loonbelastingtabellen). So this could used to check the total calculation for those different cases, and then we can have tests for the individual rate functions.

My suggestion would be to use Jest for angular (this can be a starting point: https://blog.softwaremill.com/angularjs-and-jest-three-steps-to-improve-your-legacy-frontend-tests-90674c0017e4).

**Comment by stevermeister** [comment]
Totally agree that we need to implement testing env asap.

Only I don't see a reason to use Jest. Our main focus logic(that calculation is correct), but not interface, right? So we can simply use Karma + Jasmine.

**Comment by eduardomourar** [comment]
Yes, correct, the calculation is the most important. You can use Jest for the same parts as Karma+jasmine, but it is better (faster and easier) in my opinion (you can check some more details [here](https://www.xfive.co/blog/testing-angular-faster-jest/)). To be honest I would actually move the project to Angular 8 + jest by picking up this repo I was working a long time ago: https://github.com/eduardomourar/dutch-tax-income-calculator2

**Comment by stevermeister** [comment]
I came to the conclusion that it would be really convenient to have all logic separately with tests like separate npm module that could be used in other projects. 

so I've created separate repository - https://github.com/stevermeister/dutch-tax-income-calculator-npm/blob/master/index.js (already with changes suggested in https://github.com/stevermeister/dutch-tax-income-calculator/pull/94)
please have a look. 

we can add tests there. and after finally update the version of Angular (maybe even Angular 9)  using this npm package.

> I was working a long time ago

yes, true, shame on me, I promised to find a designer and update UI and failed. But it was still deployed to https://beta.thetax.nl/

**Comment by eduardomourar** [comment]
Perfect! I have looked superficially. Let me push some changes to that repo so that we can have the full calculation being performed there (just like we would have if sending request to a backend API)

**Comment by stevermeister** [comment]
I created an issue for npm one - https://github.com/stevermeister/dutch-tax-income-calculator-npm/issues/2
