### ISSUE TITLE
13th cheque

### ISSUE THREAD

**Issue by cmalevris** [stevermeister/dutch-tax-income-calculator-old#98]
Hey guys

Love the work you doing making it super easy for us common folk.

I see an option for holiday allowance to be included when calculating which does change the values.

Is it possible to calculate if I add a 13th cheque? Would this calculation just be the same as doubling my salary for the month? No additional tax? Would it make sense to have this option aswell like holiday allowance?

**Comment by stevermeister** [comment]
if it's still actual you can reopen your issue here (new version of the application) - https://github.com/stevermeister/dutch-tax-income-calculator
