### ISSUE TITLE
Holiday allowance included in Taxable Income

### ISSUE THREAD

**Issue by vicsn** [stevermeister/dutch-tax-income-calculator-old#99]
@stevermeister thx for building the nice tool. I'm afraid there might be a mistake in the calculation. Two calls with the Dutch tax authority assured me that the holiday allowance is a part of the `Taxable Income`. I.e. As long as the annual salary including holiday allowance is above the minimum threshold indicated in the `About 30% Ruling` footnotes, employees are eligible. Can you please confirm this with your own sources so I can PR an adjustment?

**Comment by stevermeister** [comment]
@vicsn you can check test vectors here - https://github.com/stevermeister/dutch-tax-income-calculator-npm/tree/master/__tests__

**Comment by vicsn** [comment]
@stevermeister may I ask for the source of the test vectors? Two calls with the tax authority confirmed my point, I sent you an email if you want to discuss in more detail without spamming this issue.

**Comment by stevermeister** [comment]
I think we can ask @eduardomourar, he added them

**Comment by eduardomourar** [comment]
From https://www.belastingdienst.nl/wps/wcm/connect/nl/personeel-en-loon/content/hulpmiddel-loonbelastingtabellen for the normal payroll calculation, but we have no unit tests for 30% ruling. I guess you are talking about this line of code [here](https://github.com/stevermeister/dutch-tax-income-calculator-npm/blob/ef6eb375be9d91eca0cfd40c3f9f1733ca4729af/index.js#L32). So my suggestion is to make a PR to fix it and add some unit testing regarding that specific calculation, which I added but I don't know why :)

**Comment by vicsn** [comment]
I also see the issue in the calculations, the tax income calculator uses the `Tijdvaktabel` (monthly taxes) for benchmarks but not the `Tabel voor bijzondere beloningen` (yearly taxes). Both the holiday pay and 30% ruling are related to yearly taxes, not the monthly amounts.

I could add the extra table to the unit tests and fix the mistake with regards to the 30% ruling / holiday pay calculations, but I unfortunately don't feel comfortable doing that given the fact that other errors may be lingering. [Income tax is complex](https://www.belastingdienst.nl/bibliotheek/handboeken/html/boeken/HL/stappenplan.html) and this is one of the areas of taxation where I think a professional is still required to navigate the legal waters. 

Consulting a professional to check the calculations every year could help, perhaps you can find someone who wants to do it pro-bono (despite the fact that it potentially takes away work from them)?

**Comment by eduardomourar** [comment]
Just one note, both 30% ruling and holiday allowance can be part of the monthly table if you are paid per month instead of one-off (you can find this in the first "Attention" box of section 7.3.6 and check more details [here](https://www.belastingdienst.nl/bibliotheek/handboeken/html/boeken/HL/stappenplan-stap_7_loonbelasting_premie_volksverzekeringen.html#HL-07.3.6)). So I would say that we can assume the monthly table for our calculator to simplify. If one day the Dutch government makes the taxes available in a public web API, then...

**Comment by owenversteeg** [comment]
Thank you for building this tool! Lovely simple design.

I can confirm that the calculator is incorrect when checking the "Holiday allowance included" checkbox. I believe the best solution would be to simply delete the checkbox from the page, as people include it in their gross yearly income. I've checked other calculators and this is what they do - no extra checkbox for the 13th month/holiday money, just one box for your total gross income, which includes any holiday money. (For example https://www.knab.nl/financieel-overzicht/inkomstenbelasting-2020) Legally speaking, this is also the clearest option, as such holiday money is gross income just like any other paycheck.

However, if you did want to include such a checkbox, then I'd add a checkbox titled "Add 13th month" or "Add holiday allowance", which simply multiplies the annual gross income by 13/12 aka roughly ~1.0833.

**Comment by stevermeister** [comment]
if it's still actual you can reopen your issue here (new version of the application) - https://github.com/stevermeister/dutch-tax-income-calculator
